@echo off
REM GemNet Data Migration Script - Local MongoDB to Atlas

echo 🔄 GemNet Database Migration Tool
echo ================================

echo.
echo This script will help you migrate your local GemNet database to MongoDB Atlas
echo.

REM Check if MongoDB tools are available
where mongodump >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo ❌ MongoDB tools not found. Please install MongoDB Database Tools:
    echo    https://www.mongodb.com/try/download/database-tools
    echo.
    pause
    exit /b 1
)

echo ✅ MongoDB tools found

REM Create backup directory
if not exist "database-backup" mkdir database-backup

echo.
echo 📦 Step 1: Creating backup of local database...
mongodump --host localhost:27017 --db gemnet_db --out database-backup

if %ERRORLEVEL% neq 0 (
    echo ❌ Failed to backup local database. Make sure MongoDB is running locally.
    pause
    exit /b 1
)

echo ✅ Local database backed up successfully

echo.
echo 📋 Step 2: Atlas Connection Setup
echo.
echo Please provide your MongoDB Atlas connection details:
echo (Get these from Atlas Dashboard -> Connect -> Connect your application)
echo.

set /p ATLAS_USERNAME="Enter Atlas Username (e.g., gemnet_admin): "
set /p ATLAS_PASSWORD="Enter Atlas Password: "
set /p ATLAS_CLUSTER="Enter Atlas Cluster URL (e.g., gemnet-cluster.xxxxx.mongodb.net): "

REM Construct Atlas connection string
set ATLAS_URI=mongodb+srv://%ATLAS_USERNAME%:%ATLAS_PASSWORD%@%ATLAS_CLUSTER%/gemnet_db?retryWrites=true

echo.
echo 🧪 Step 3: Testing Atlas connection...
mongosh "%ATLAS_URI%" --eval "db.adminCommand('ping')" --quiet

if %ERRORLEVEL% neq 0 (
    echo ❌ Failed to connect to Atlas. Please check your credentials and try again.
    pause
    exit /b 1
)

echo ✅ Atlas connection successful

echo.
echo 📤 Step 4: Uploading data to Atlas...
echo Warning: This will replace any existing data in Atlas!
echo.

choice /M "Continue with data upload"
if %ERRORLEVEL% equ 2 (
    echo Operation cancelled.
    pause
    exit /b 0
)

REM Restore to Atlas
mongorestore --uri "%ATLAS_URI%" database-backup/gemnet_db --drop

if %ERRORLEVEL% neq 0 (
    echo ❌ Failed to upload data to Atlas.
    pause
    exit /b 1
)

echo.
echo ✅ Migration completed successfully!
echo.
echo 📝 Next Steps:
echo    1. Update your application.properties with Atlas connection string:
echo       spring.data.mongodb.uri=%ATLAS_URI%
echo.
echo    2. Share this connection string with your contributors
echo.
echo    3. Test your application with the new Atlas database
echo.

REM Create application.properties update
echo.
echo 🔧 Creating application-atlas.properties with your connection string...

(
echo # MongoDB Atlas Configuration - Generated by migration script
echo # Replace your existing MongoDB configuration with this
echo.
echo spring.data.mongodb.uri=%ATLAS_URI%
echo.
echo # Remove these local MongoDB settings when using Atlas:
echo # spring.data.mongodb.host=localhost
echo # spring.data.mongodb.port=27017
echo # spring.data.mongodb.database=gemnet_db
) > application-atlas-configured.properties

echo ✅ Created application-atlas-configured.properties
echo.
echo 🎉 Migration Complete!
echo Your local GemNet database has been successfully migrated to MongoDB Atlas.
echo Contributors can now use the same database by using the Atlas connection string.
echo.

pause